apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dotnet-app-prod
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/your-org/06ArgoCD-Multi-Env-EKS-Dotnet-App.git
    targetRevision: HEAD
    path: charts
    helm:
      valueFiles:
        - prod/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: dotnet-app-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true 